#ifndef SYSTEM_GLOBAL_DEFINITIONS_H
#define SYSTEM_GLOBAL_DEFINITIONS_H

#define PERIODO_PWM_MS 10 

#define INATIVO 0
#define ATIVO 1
#define DESATIVANDO 2
#define ATIVANDO 3

#define USUARIO_INICIO 0
#define USUARIO_ESCOLHA_MODO 1
#define USUARIO_SENTIDO 2
#define USUARIO_FEEDBACK_POT 3
#define USUARIO_FEEDBACK_TECLADO 4
#define USUARIO_FIM 5



#endif